<?php

namespace Tests\Feature\Http\Controllers;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UserControllerTest extends TestCase
{
    use RefreshDatabase;

    private Model $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
    }

    public function testStore(): void
    {
        $response = $this
            //->actingAs($this->user)
            ->postJson('/api/v1/users', [
                'name' => 'user',
                'email' => 'user@example.com',
                'password' => '12345678',
            ]);

        $response->assertSuccessful();
//        $response->assertJsonFragment(['title' => $title]);
//
//        $this->assertDatabaseHas('teams', ['title' => $title]);
    }
}
